-- EggyPDF Career Pro V1 billing, credits and creator-code foundation
-- Run this AFTER 001_career_accounts.sql in Supabase SQL Editor.
-- Server-side writes use the service-role key. Browser clients receive read-only
-- access to their own entitlement / wallet / ledger rows through RLS.

create extension if not exists pgcrypto;

-- Extend the existing account entitlement into a subscription-aware record.
alter table public.career_entitlements
  add column if not exists plan text,
  add column if not exists source text not null default 'dodo',
  add column if not exists dodo_subscription_id text,
  add column if not exists current_period_start timestamptz,
  add column if not exists current_period_end timestamptz,
  add column if not exists cancel_at_period_end boolean not null default false,
  add column if not exists access_ends_at timestamptz,
  add column if not exists monthly_credits integer not null default 2000;

alter table public.career_entitlements
  drop constraint if exists career_entitlements_status_check;
alter table public.career_entitlements
  add constraint career_entitlements_status_check
  check (status in ('inactive','active','on_hold','cancelled','expired','revoked','refunded'));

alter table public.career_entitlements
  drop constraint if exists career_entitlements_plan_check;
alter table public.career_entitlements
  add constraint career_entitlements_plan_check
  check (plan is null or plan in ('monthly','yearly','creator','admin'));

alter table public.career_entitlements
  drop constraint if exists career_entitlements_source_check;
alter table public.career_entitlements
  add constraint career_entitlements_source_check
  check (source in ('dodo','creator','admin'));

create unique index if not exists career_entitlements_dodo_subscription_uidx
on public.career_entitlements(dodo_subscription_id)
where dodo_subscription_id is not null;

create table if not exists public.career_credit_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0 check (balance >= 0),
  monthly_allowance integer not null default 2000 check (monthly_allowance >= 0),
  cycle_start timestamptz not null default now(),
  cycle_end timestamptz not null default (now() + interval '1 month'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.career_credit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('grant','reset','debit','refund','adjustment')),
  action text not null,
  amount integer not null,
  balance_after integer not null check (balance_after >= 0),
  request_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists career_credit_events_request_uidx
on public.career_credit_events(user_id, request_key, event_type)
where request_key is not null;

create index if not exists career_credit_events_user_created_idx
on public.career_credit_events(user_id, created_at desc);

create table if not exists public.creator_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  label text,
  duration_months integer check (duration_months is null or duration_months > 0),
  lifetime boolean not null default false,
  monthly_credits integer not null default 2000 check (monthly_credits > 0),
  expires_at timestamptz,
  max_redemptions integer not null default 1 check (max_redemptions > 0),
  redemption_count integer not null default 0 check (redemption_count >= 0),
  active boolean not null default true,
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint creator_codes_duration_check check (lifetime or duration_months is not null)
);

create table if not exists public.creator_code_redemptions (
  id bigint generated by default as identity primary key,
  code_id uuid not null references public.creator_codes(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  redeemed_at timestamptz not null default now(),
  access_ends_at timestamptz,
  unique(code_id, user_id)
);

create index if not exists creator_code_redemptions_user_idx
on public.creator_code_redemptions(user_id, redeemed_at desc);

-- Stores only webhook IDs / event names for idempotency. Raw payment payloads are
-- intentionally not retained here.
create table if not exists public.career_billing_webhooks (
  webhook_id text primary key,
  event_type text not null,
  processed_at timestamptz not null default now()
);

-- Keep updated_at consistent with the tables created in migration 001.
drop trigger if exists career_credit_wallets_set_updated_at on public.career_credit_wallets;
create trigger career_credit_wallets_set_updated_at
before update on public.career_credit_wallets
for each row execute function public.set_updated_at();

drop trigger if exists creator_codes_set_updated_at on public.creator_codes;
create trigger creator_codes_set_updated_at
before update on public.creator_codes
for each row execute function public.set_updated_at();

alter table public.career_credit_wallets enable row level security;
alter table public.career_credit_events enable row level security;
alter table public.creator_codes enable row level security;
alter table public.creator_code_redemptions enable row level security;
alter table public.career_billing_webhooks enable row level security;

drop policy if exists "Users can read own Career Pro wallet" on public.career_credit_wallets;
create policy "Users can read own Career Pro wallet"
on public.career_credit_wallets for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read own Career Pro credit events" on public.career_credit_events;
create policy "Users can read own Career Pro credit events"
on public.career_credit_events for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read own creator redemptions" on public.creator_code_redemptions;
create policy "Users can read own creator redemptions"
on public.creator_code_redemptions for select
to authenticated
using (auth.uid() = user_id);

-- creator_codes and career_billing_webhooks intentionally have no browser
-- policies. They are backend-only tables.

-- Refresh a wallet when its monthly credit cycle has rolled over. This gives
-- annual subscribers 2,000 fresh credits each month without requiring a Dodo
-- billing event every month.
create or replace function public.refresh_career_credit_cycle(p_user uuid)
returns table(balance integer, monthly_allowance integer, cycle_start timestamptz, cycle_end timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  w public.career_credit_wallets%rowtype;
  e public.career_entitlements%rowtype;
begin
  select * into e
  from public.career_entitlements
  where user_id = p_user
  for update;

  if not found or e.status <> 'active' or (e.access_ends_at is not null and e.access_ends_at <= now()) then
    raise exception 'Career Pro access is not active.' using errcode = 'P0001';
  end if;

  insert into public.career_credit_wallets(user_id, balance, monthly_allowance, cycle_start, cycle_end)
  values (p_user, greatest(e.monthly_credits, 0), greatest(e.monthly_credits, 0), now(), now() + interval '1 month')
  on conflict (user_id) do nothing;

  select * into w
  from public.career_credit_wallets
  where user_id = p_user
  for update;

  if w.cycle_end <= now() then
    update public.career_credit_wallets
    set balance = monthly_allowance,
        cycle_start = now(),
        cycle_end = now() + interval '1 month'
    where user_id = p_user
    returning * into w;

    insert into public.career_credit_events(user_id,event_type,action,amount,balance_after,metadata)
    values (p_user,'reset','monthly_cycle',w.monthly_allowance,w.balance,jsonb_build_object('cycle_end',w.cycle_end));
  end if;

  return query select w.balance, w.monthly_allowance, w.cycle_start, w.cycle_end;
end;
$$;

-- Atomic, idempotent debit. request_key prevents one browser retry from being
-- charged twice.
create or replace function public.consume_career_credits(
  p_user uuid,
  p_amount integer,
  p_action text,
  p_request_key text
)
returns table(balance integer, charged integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  w public.career_credit_wallets%rowtype;
  prior public.career_credit_events%rowtype;
begin
  if p_amount <= 0 then
    raise exception 'Credit amount must be positive.' using errcode = '22023';
  end if;
  if coalesce(trim(p_request_key),'') = '' then
    raise exception 'A request key is required.' using errcode = '22023';
  end if;

  perform public.refresh_career_credit_cycle(p_user);

  select * into prior
  from public.career_credit_events
  where user_id = p_user and request_key = p_request_key and event_type = 'debit'
  limit 1;
  if found then
    return query select prior.balance_after, 0;
    return;
  end if;

  select * into w
  from public.career_credit_wallets
  where user_id = p_user
  for update;

  if w.balance < p_amount then
    raise exception 'Not enough Career Pro credits.' using errcode = 'P0001';
  end if;

  update public.career_credit_wallets
  set balance = balance - p_amount
  where user_id = p_user
  returning * into w;

  insert into public.career_credit_events(user_id,event_type,action,amount,balance_after,request_key)
  values (p_user,'debit',coalesce(nullif(trim(p_action),''),'ai_action'),-p_amount,w.balance,p_request_key);

  return query select w.balance, p_amount;
end;
$$;

create or replace function public.refund_career_credits(
  p_user uuid,
  p_request_key text
)
returns table(balance integer, refunded integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  debit_row public.career_credit_events%rowtype;
  refund_row public.career_credit_events%rowtype;
  w public.career_credit_wallets%rowtype;
  amount_to_refund integer;
begin
  select * into debit_row
  from public.career_credit_events
  where user_id = p_user and request_key = p_request_key and event_type = 'debit'
  limit 1;

  if not found then
    return query select coalesce((select cw.balance from public.career_credit_wallets cw where cw.user_id=p_user),0), 0;
    return;
  end if;

  select * into refund_row
  from public.career_credit_events
  where user_id = p_user and request_key = p_request_key and event_type = 'refund'
  limit 1;
  if found then
    return query select refund_row.balance_after, 0;
    return;
  end if;

  amount_to_refund := abs(debit_row.amount);
  update public.career_credit_wallets
  set balance = balance + amount_to_refund
  where user_id = p_user
  returning * into w;

  insert into public.career_credit_events(user_id,event_type,action,amount,balance_after,request_key,metadata)
  values (p_user,'refund',debit_row.action,amount_to_refund,w.balance,p_request_key,jsonb_build_object('reason','failed_ai_request'));

  return query select w.balance, amount_to_refund;
end;
$$;

-- Creator codes are claimed atomically by the authenticated account. A current
-- paid Dodo subscriber is never overwritten by a promotional code.
create or replace function public.redeem_creator_code(p_user uuid, p_code text)
returns table(
  success boolean,
  message text,
  plan text,
  credits integer,
  access_ends_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.creator_codes%rowtype;
  existing public.career_entitlements%rowtype;
  end_at timestamptz;
begin
  select * into c
  from public.creator_codes
  where upper(code) = upper(trim(p_code))
  for update;

  if not found then
    return query select false,'Invalid creator code.'::text,null::text,0,null::timestamptz;
    return;
  end if;

  if not c.active or c.revoked then
    return query select false,'This creator code is not active.'::text,null::text,0,null::timestamptz;
    return;
  end if;
  if c.expires_at is not null and c.expires_at <= now() then
    return query select false,'This creator code has expired.'::text,null::text,0,null::timestamptz;
    return;
  end if;

  if exists(select 1 from public.creator_code_redemptions where code_id=c.id and user_id=p_user) then
    select * into existing from public.career_entitlements where user_id=p_user;
    return query select true,'Creator code already redeemed on this account.'::text,'creator'::text,
      coalesce(existing.monthly_credits,c.monthly_credits), existing.access_ends_at;
    return;
  end if;

  if c.redemption_count >= c.max_redemptions then
    return query select false,'This creator code has already been claimed.'::text,null::text,0,null::timestamptz;
    return;
  end if;

  select * into existing from public.career_entitlements where user_id=p_user for update;
  if found and existing.status='active' and existing.source='dodo'
     and (existing.access_ends_at is null or existing.access_ends_at > now()) then
    return query select false,'This account already has an active paid Career Pro subscription.'::text,
      existing.plan, existing.monthly_credits, existing.access_ends_at;
    return;
  end if;

  end_at := case when c.lifetime then null else now() + make_interval(months => c.duration_months) end;

  insert into public.creator_code_redemptions(code_id,user_id,access_ends_at)
  values (c.id,p_user,end_at);

  update public.creator_codes
  set redemption_count = redemption_count + 1
  where id = c.id;

  insert into public.career_entitlements(
    user_id,status,product_id,plan,source,purchased_at,current_period_start,current_period_end,
    cancel_at_period_end,access_ends_at,monthly_credits
  ) values (
    p_user,'active','creator-code','creator','creator',now(),now(),
    case when c.lifetime then null else least(end_at, now()+interval '1 month') end,
    false,end_at,c.monthly_credits
  )
  on conflict (user_id) do update set
    status='active', product_id='creator-code', plan='creator', source='creator',
    dodo_checkout_id=null, dodo_payment_id=null, dodo_subscription_id=null,
    purchased_at=now(), current_period_start=now(),
    current_period_end=excluded.current_period_end,
    cancel_at_period_end=false, access_ends_at=end_at, monthly_credits=c.monthly_credits;

  insert into public.career_credit_wallets(user_id,balance,monthly_allowance,cycle_start,cycle_end)
  values (p_user,c.monthly_credits,c.monthly_credits,now(),now()+interval '1 month')
  on conflict (user_id) do update set
    balance=excluded.balance,
    monthly_allowance=excluded.monthly_allowance,
    cycle_start=excluded.cycle_start,
    cycle_end=excluded.cycle_end;

  insert into public.career_credit_events(user_id,event_type,action,amount,balance_after,metadata)
  values (p_user,'grant','creator_code',c.monthly_credits,c.monthly_credits,jsonb_build_object('creator_code_id',c.id));

  return query select true,'Creator code applied.'::text,'creator'::text,c.monthly_credits,end_at;
end;
$$;
